"""Exercise the built Windows bundle offline from a relocated path with spaces.

Requires an UNCONFIGURED bundle with its model already downloaded. No real VPS,
Docker, external provider, installed target Python, or inference call is used.
"""
import json
import os
from pathlib import Path
import subprocess
import time

import psutil


ROOT = Path(__file__).resolve().parents[2]


def main():
    original = ROOT / "out/Market-AI-Portable"
    relocated = ROOT / "out/Market AI USB smoke"
    for path in (original, relocated):
        if not path.resolve().is_relative_to((ROOT / "out").resolve()):
            raise RuntimeError("Test paths must remain in the workspace output directory")
    if relocated.exists() or any((original / "config").iterdir()):
        raise RuntimeError("Use an unconfigured bundle; no existing credentials are modified")
    model = original / "data/models/manifests/registry.ollama.ai/library/qwen3/4b-instruct"
    if not model.is_file():
        raise RuntimeError("Prepare the model before this offline lifecycle test")
    state_path = original / "data/state.json"
    before = json.loads(state_path.read_text()) if state_path.exists() else {}
    if before.get("pid") and psutil.pid_exists(before["pid"]):
        try:
            process = psutil.Process(before["pid"])
            if process.create_time() == before["created_at"]:
                raise RuntimeError("Stop the portable worker before this test")
        except psutil.NoSuchProcess:
            pass
    unrelated = {p.pid: p.create_time() for p in psutil.process_iter()
        if p.name().lower() == "ollama.exe"}
    original.rename(relocated)
    binary = relocated / "runtime/worker/market-ai-worker.exe"
    env = dict(os.environ)
    env["PATH"] = str(Path(os.environ["SystemRoot"]) / "System32")

    def command(*args):
        result = subprocess.run([str(binary), *args], cwd=relocated, env=env,
            capture_output=True, text=True, timeout=40)
        if result.returncode:
            raise RuntimeError(f"Native action failed: {args[0]} (no credentials printed)")
        return result.stdout

    try:
        assert "Worker autonome valide" in command("self-test")
        command("configure", "--site", "https://127.0.0.1:9")
        saved = (relocated / "config/worker.json").read_bytes()
        command("configure")
        assert saved == (relocated / "config/worker.json").read_bytes()
        command("start")
        deadline = time.monotonic() + 180
        while time.monotonic() < deadline:
            state = json.loads((relocated / "data/state.json").read_text())
            if state["phase"] == "ready":
                break
            assert state["phase"] != "error", "Native supervisor failed"
            time.sleep(1)
        else:
            raise RuntimeError("Native worker readiness timeout")
        pid = state["pid"]
        command("start")
        assert json.loads((relocated / "data/state.json").read_text())["pid"] == pid
        supervisor = psutil.Process(pid)
        children = supervisor.children(recursive=True)
        assert any(p.name().lower() == "ollama.exe" for p in children)
        assert "actif" in command("status")
        # A real .bat, including its pause, must also work from this new path.
        result = subprocess.run([str(Path(os.environ["SystemRoot"]) / "System32/cmd.exe"),
            "/d", "/c", "Etat-IA.bat"], input="\n", cwd=relocated, env=env,
            capture_output=True, text=True, timeout=20)
        assert result.returncode == 0 and "actif" in result.stdout
        command("stop")
        assert not supervisor.is_running()
        assert all(not p.is_running() for p in children)
        for pid, created in unrelated.items():
            assert psutil.Process(pid).create_time() == created, "An unrelated Ollama was changed"
        assert "Aucune IA" in command("stop")
        assert (relocated / "data/models/manifests").exists()
        print("Native USB smoke passed: relocated path, no Python/Docker in PATH,")
        print("stable configuration, idempotent start, real batch, scoped shutdown.")
    finally:
        command("stop")
        # Only credentials generated by this isolated smoke are removed.
        for name in ("worker.json", "vps-worker.txt"):
            (relocated / "config" / name).unlink(missing_ok=True)
        relocated.rename(original)


if __name__ == "__main__":
    main()
