param([string]$Username = 'administrateur', [switch]$PrepareOnly)
$ErrorActionPreference = 'Stop'
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location -LiteralPath $projectRoot
$overridePath = Join-Path $projectRoot 'docker-compose.override.yml'
if (Test-Path -LiteralPath $overridePath) { throw 'Un override Docker existe déjà. Il est conservé ; examiner son contenu avant toute activation.' }
if ($Username -notmatch '^[a-z0-9_.-]{3,80}$') { throw 'Identifiant invalide.' }
$privatePath = Join-Path $projectRoot 'private-data/local-access'
New-Item -ItemType Directory -Force -Path $privatePath | Out-Null
$resolvedPrivate = (Resolve-Path -LiteralPath $privatePath).Path
if (-not $resolvedPrivate.StartsWith($projectRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase)) { throw 'Dossier privé hors du projet.' }
# Restrict generated secrets to the current Windows account and SYSTEM.
$ownerSid = [Security.Principal.WindowsIdentity]::GetCurrent().User.Value
& icacls $resolvedPrivate /inheritance:r /grant:r "*${ownerSid}:(OI)(CI)F" '*S-1-5-18:(OI)(CI)F' | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'Protection du dossier privé impossible.' }
& docker compose build backend
if ($LASTEXITCODE -ne 0) { throw 'Construction du backend échouée.' }
& docker build -t market-ai-backup ./deploy/backup
if ($LASTEXITCODE -ne 0) { throw 'Construction de sauvegarde échouée.' }
$keyPath = Join-Path $resolvedPrivate 'backup-identity.key'
if (-not (Test-Path -LiteralPath $keyPath)) {
    & docker run --rm -v "${resolvedPrivate}:/keys" --entrypoint age-keygen market-ai-backup -o /keys/backup-identity.key
    if ($LASTEXITCODE -ne 0) { throw 'Création de clé impossible.' }
}
$recipient = (& docker run --rm -v "${resolvedPrivate}:/keys:ro" --entrypoint age-keygen market-ai-backup -y /keys/backup-identity.key | Out-String).Trim()
if ($LASTEXITCODE -ne 0 -or $recipient -notmatch '^age1[a-z0-9]+$') { throw 'Destinataire public invalide.' }
& docker compose run --rm --no-deps -v "${resolvedPrivate}:/bootstrap" --entrypoint python backend -m app.cli.bootstrap_local_account $Username --credential-file /bootstrap/first-login.json
if ($LASTEXITCODE -ne 0) { throw 'Création du compte échouée. Authentification non activée.' }
$backup = [IO.File]::ReadAllText((Join-Path $projectRoot 'docker-compose.backup.yml'))
$backup = $backup.Replace('services:', '').Replace('${BACKUP_RECIPIENT:?Set your public age recipient}', $recipient).TrimStart("`r", "`n")
$config = "# Generated by Enable-LocalWorkspace.ps1 - local HTTP only`nservices:`n  backend:`n    environment:`n      AUTH_ENABLED: 'true'`n      AUTH_COOKIE_SECURE: 'false'`n      ENVIRONMENT: development`n  scheduler:`n    environment:`n      AUTH_ENABLED: 'true'`n      AUTH_COOKIE_SECURE: 'false'`n      ENVIRONMENT: development`n" + $backup
[IO.File]::WriteAllText($overridePath, $config, [Text.UTF8Encoding]::new($false))
& docker compose config --quiet
if ($LASTEXITCODE -ne 0) { throw 'Configuration locale invalide. Aucun redémarrage effectué.' }
Write-Host 'Configuration locale préparée sans modifier .env. Fichier privé : private-data/local-access/first-login.json'
Write-Host 'Conserver la clé de sauvegarde hors de la machine : private-data/local-access/backup-identity.key'
if (-not $PrepareOnly) {
    & docker compose up -d --build backend scheduler frontend
    if ($LASTEXITCODE -ne 0) { throw 'Redémarrage incomplet : vérifier docker compose ps.' }
    & docker compose up -d --build backup
    if ($LASTEXITCODE -ne 0) { throw 'Démarrage de la sauvegarde incomplet : vérifier docker compose ps.' }
    Write-Host 'Accès et sauvegardes activés en local. Changer le mot de passe dans Mon espace après connexion.'
}
